version: '2'

services:
  dev-panel:
       build:
          context: ../../.
          dockerfile: ./docker/development/Dockerfile
       volumes:
         - ../../.:/code/
       container_name: dev-panel
       command: npm run dev
       environment:
         - APP_ENV=dev
         - TERM=xterm-256color
       privileged: true
       expose:
         - "80"
       ports:
         - "8006:8080"
